# $OpenBSD$

COMMENT =	Debian Almquist shell, POSIX-compliant

DISTNAME =	dash-0.5.7
CATEGORIES =	shells

HOMEPAGE =	http://gondor.apana.org.au/~herbert/dash/
MASTER_SITES =	${HOMEPAGE}files/

# BSD, GPLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

USE_GROFF =		Yes
USE_GMAKE =		Yes
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
